---
- hosts: all
  user: vagrant
  sudo: yes
  vars:
    root_db_password: vagrant
  tasks:

    - name: apt update
      apt: update_cache=yes

    - name: git install
      apt: pkg=git state=installed

    - name: apache install
      apt: pkg=apache2 state=installed
    - template: src=./template/apache2/sites-available/000-default.conf dest=/etc/apache2/sites-available/000-default.conf owner=root mode=0600

    - name: php install
      apt: pkg={{item}} state=installed
      with_items:
      - php5
      - php5-cgi
      - php5-cli
      - libapache2-mod-php5
      - php5-common
      - php-pear
      - php5-mysql
      - php5-curl
      - php5-gd
      - imagemagick
      - php5-imagick
      - php5-mcrypt
    - template: src=./template/php/php.ini dest=/etc/php5/apache2/php.ini owner=root mode=0600
    - service: name=apache2 state=restarted

    - name: apache install
      apt: pkg=apache2 state=installed

    - name: mysql install
      apt: pkg={{item}} state=installed
      with_items:
      - mysql-server

